# theme.toml for Alchemista hugo theme

name = "Alchemista-hugo-theme"
license = "MIT"
licenselink = "https://github.com/StaticMania/Alchemista-hugo/blob/master/LICENSE"
description = "Alchemista Hugo – App Landing Page is the perfect app showcase Hugo Theme. Alchemista is a better way to present your modern business and app showcasing. It’s easy to customize and also well documented. And compatible with Desktop, laptop, mobile, and also compatible with major browsers. We follow the modern design system to craft the template."
homepage = "https://Alchemista-hugo.staticmania.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Static Mania"
  homepage = "https://staticmania.com/"